name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - 27.2
        - snapshot

    steps:
      - uses: actions/checkout@v2

      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Test
        run: emacs -Q -batch -L . -L ./test -l ert -l unicode-block-tests -f ert-run-tests-batch-and-exit
